<template>
  <!-- Generated by IcoMoon.io -->
<svg xmlns="http://www.w3.org/2000/svg" width="9.001" height="18" viewBox="0 0 9.001 18">
  <path id="facebook_3_" data-name="facebook (3)" d="M13.545,2.989h1.643V.127A21.219,21.219,0,0,0,12.794,0C10.424,0,8.8,1.49,8.8,4.229V6.75H6.187v3.2H8.8V18h3.205V9.95h2.509l.4-3.2H12.006v-2.2C12.007,3.622,12.256,2.989,13.545,2.989Z" transform="translate(-6.187)" fill="#5a5b88"/>
</svg>

</template>
