<template>
  <!-- Generated by IcoMoon.io -->
  <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
    <title>linkdn-01</title>
    <path
      fill="none"
      stroke="currentColor"
      stroke-linejoin="miter"
      stroke-linecap="butt"
      stroke-miterlimit="10"
      stroke-width="1.3043"
      d="M31.348 16c0 8.476-6.871 15.348-15.348 15.348s-15.348-6.871-15.348-15.348c0-8.476 6.871-15.348 15.348-15.348s15.348 6.871 15.348 15.348z"
    />
    <path
      fill="currentColor"
      d="M8.348 23.652h2.87v-11.478h-2.87v11.478zM19.826 12.174c-2.478 0.043-3.696 1.826-3.826 1.913v-1.913h-2.87v11.522h2.87v-6.739c0-0.261 0.609-2.217 2.87-1.913 1.217 0.087 1.87 1.696 1.913 1.913v6.696h2.87v-7.957c-0.087-1.13-0.652-3.478-3.826-3.522zM9.783 8.304c-0.783 0-1.435 0.652-1.435 1.435s0.652 1.435 1.435 1.435c0.783 0 1.435-0.652 1.435-1.435s-0.652-1.435-1.435-1.435z"
    />
  </svg>
</template>
