<template>
  <!-- Generated by IcoMoon.io -->
  <svg
    version="1.1"
    xmlns="http://www.w3.org/2000/svg"
    width="32"
    height="32"
    viewBox="0 0 32 32"
  >
    <path
      :class="{ st0: stroke }"
      fill="currentColor"
      d="M16 0c-6.387 0-11.588 5.2-11.588 11.588 0 7.931 10.369 19.575 10.813 20.063 0.412 0.462 1.138 0.462 1.55 0 0.444-0.494 10.813-12.131 10.813-20.063 0-6.388-5.2-11.588-11.588-11.588zM16 17.419c-3.213 0-5.831-2.619-5.831-5.831s2.619-5.831 5.831-5.831 5.831 2.619 5.831 5.831-2.619 5.831-5.831 5.831z"
    ></path>
  </svg>
</template>

<script>
export default {
  props: {
    stroke: {
      type: Boolean,
      default: false
    }
  }
}
</script>
<style  scoped>
.st0 {
  stroke: blue;
  stroke-width: 1.5;
  stroke-miterlimit: 10;
}
</style>
